$settingsPath = "C:\Users\hamma\Downloads\phantom-theme\phantom-theme-v2.2.0\config\settings_data.json"
$json = Get-Content $settingsPath -Raw | ConvertFrom-Json

$presets = [ordered]@{
  "PHANTOM Minimal" = [ordered]@{
    "ph_color_body_bg" = "#f5f5f0"
    "ph_color_body_text" = "#2a2a28"
    "ph_color_price" = "#2a2a28"
    "ph_color_savings_text" = "#c44d4d"
    "ph_color_borders" = "#e0ddd5"
    "ph_color_button" = "#2a2a28"
    "ph_color_button_text" = "#f5f5f0"
    "ph_color_sale_tag" = "#c44d4d"
    "ph_color_sale_tag_text" = "#ffffff"
    "ph_color_cart_dot" = "#c44d4d"
    "ph_color_header" = "#f5f5f0"
    "ph_color_header_text" = "#2a2a28"
    "ph_color_announcement" = "#2a2a28"
    "ph_color_announcement_text" = "#f5f5f0"
    "ph_color_footer" = "#2a2a28"
    "ph_color_footer_text" = "#f5f5f0"
    "ph_color_drawer_background" = "#f5f5f0"
    "ph_color_drawer_text" = "#2a2a28"
    "ph_color_drawer_border" = "#e0ddd5"
    "ph_color_drawer_button" = "#2a2a28"
    "ph_color_drawer_button_text" = "#f5f5f0"
    "ph_color_modal_overlays" = "#e0ddd5"
    "ph_color_small_image_bg" = "#f5f5f0"
    "ph_color_large_image_bg" = "#e0ddd5"
    "ph_color_image_text" = "#2a2a28"
    "ph_color_image_overlay" = "#000000"
    "ph_color_image_overlay_opacity" = 5
    "type_header_font" = "ivypresto-display, Georgia, serif"
    "type_base_font" = "jost, Helvetica, sans-serif"
    "type_header_spacing" = "50"
    "type_header_line_height" = 1.2
    "type_header_capitalize" = $false
    "type_headers_align_text" = "left"
    "type_base_size" = 16
    "type_navigation_style" = "body"
    "type_navigation_size" = 14
    "type_navigation_capitalize" = $false
    "type_product_capitalize" = $false
    "type_collection_size" = 22
    "button_style" = "round-slight"
    "icon_weight" = "2px"
    "icon_linecaps" = "round"
  }
  "PHANTOM Editorial" = [ordered]@{
    "ph_color_body_bg" = "#1a1a1a"
    "ph_color_body_text" = "#e8e4dd"
    "ph_color_price" = "#e8e4dd"
    "ph_color_savings_text" = "#bf8f6b"
    "ph_color_borders" = "#33332e"
    "ph_color_button" = "#bf8f6b"
    "ph_color_button_text" = "#1a1a1a"
    "ph_color_sale_tag" = "#bf8f6b"
    "ph_color_sale_tag_text" = "#1a1a1a"
    "ph_color_cart_dot" = "#bf8f6b"
    "ph_color_header" = "#1a1a1a"
    "ph_color_header_text" = "#e8e4dd"
    "ph_color_announcement" = "#bf8f6b"
    "ph_color_announcement_text" = "#1a1a1a"
    "ph_color_footer" = "#141414"
    "ph_color_footer_text" = "#e8e4dd"
    "ph_color_drawer_background" = "#1a1a1a"
    "ph_color_drawer_text" = "#e8e4dd"
    "ph_color_drawer_border" = "#33332e"
    "ph_color_drawer_button" = "#bf8f6b"
    "ph_color_drawer_button_text" = "#1a1a1a"
    "ph_color_modal_overlays" = "#000000"
    "ph_color_small_image_bg" = "#2a2a27"
    "ph_color_large_image_bg" = "#2a2a27"
    "ph_color_image_text" = "#ffffff"
    "ph_color_image_overlay" = "#000000"
    "ph_color_image_overlay_opacity" = 25
    "type_header_font" = "ivypresto-display, Georgia, serif"
    "type_base_font" = "jost, Helvetica, sans-serif"
    "type_header_spacing" = "100"
    "type_header_line_height" = 1.15
    "type_header_capitalize" = $false
    "type_headers_align_text" = "center"
    "type_base_size" = 17
    "type_navigation_style" = "heading"
    "type_navigation_size" = 13
    "type_navigation_capitalize" = $true
    "type_product_capitalize" = $false
    "type_collection_size" = 20
    "button_style" = "pill"
    "icon_weight" = "2px"
    "icon_linecaps" = "round"
  }
  "PHANTOM Bold" = [ordered]@{
    "ph_color_body_bg" = "#ffffff"
    "ph_color_body_text" = "#0d0d0d"
    "ph_color_price" = "#0d0d0d"
    "ph_color_savings_text" = "#e63946"
    "ph_color_borders" = "#0d0d0d"
    "ph_color_button" = "#0d0d0d"
    "ph_color_button_text" = "#ffffff"
    "ph_color_sale_tag" = "#e63946"
    "ph_color_sale_tag_text" = "#ffffff"
    "ph_color_cart_dot" = "#e63946"
    "ph_color_header" = "#ffffff"
    "ph_color_header_text" = "#0d0d0d"
    "ph_color_announcement" = "#e63946"
    "ph_color_announcement_text" = "#ffffff"
    "ph_color_footer" = "#0d0d0d"
    "ph_color_footer_text" = "#ffffff"
    "ph_color_drawer_background" = "#ffffff"
    "ph_color_drawer_text" = "#0d0d0d"
    "ph_color_drawer_border" = "#0d0d0d"
    "ph_color_drawer_button" = "#0d0d0d"
    "ph_color_drawer_button_text" = "#ffffff"
    "ph_color_modal_overlays" = "#cccccc"
    "ph_color_small_image_bg" = "#f0f0f0"
    "ph_color_large_image_bg" = "#0d0d0d"
    "ph_color_image_text" = "#ffffff"
    "ph_color_image_overlay" = "#000000"
    "ph_color_image_overlay_opacity" = 15
    "type_header_font" = "jost, Helvetica, sans-serif"
    "type_base_font" = "jost, Helvetica, sans-serif"
    "type_header_spacing" = "0"
    "type_header_line_height" = 1.0
    "type_header_capitalize" = $true
    "type_headers_align_text" = "center"
    "type_base_size" = 18
    "type_navigation_style" = "heading"
    "type_navigation_size" = 15
    "type_navigation_capitalize" = $true
    "type_product_capitalize" = $true
    "type_collection_size" = 24
    "button_style" = "square"
    "icon_weight" = "4px"
    "icon_linecaps" = "miter"
  }
  "PHANTOM Luxury" = [ordered]@{
    "ph_color_body_bg" = "#fcfbf7"
    "ph_color_body_text" = "#1a1410"
    "ph_color_price" = "#1a1410"
    "ph_color_savings_text" = "#b38b5b"
    "ph_color_borders" = "#d4cdc0"
    "ph_color_button" = "#b38b5b"
    "ph_color_button_text" = "#ffffff"
    "ph_color_sale_tag" = "#b38b5b"
    "ph_color_sale_tag_text" = "#ffffff"
    "ph_color_cart_dot" = "#b38b5b"
    "ph_color_header" = "#fcfbf7"
    "ph_color_header_text" = "#1a1410"
    "ph_color_announcement" = "#1a1410"
    "ph_color_announcement_text" = "#fcfbf7"
    "ph_color_footer" = "#1a1410"
    "ph_color_footer_text" = "#d4cdc0"
    "ph_color_drawer_background" = "#fcfbf7"
    "ph_color_drawer_text" = "#1a1410"
    "ph_color_drawer_border" = "#d4cdc0"
    "ph_color_drawer_button" = "#b38b5b"
    "ph_color_drawer_button_text" = "#ffffff"
    "ph_color_modal_overlays" = "#d4cdc0"
    "ph_color_small_image_bg" = "#fcfbf7"
    "ph_color_large_image_bg" = "#1a1410"
    "ph_color_image_text" = "#1a1410"
    "ph_color_image_overlay" = "#000000"
    "ph_color_image_overlay_opacity" = 10
    "type_header_font" = "ivypresto-display, Georgia, serif"
    "type_base_font" = "ivypresto-display, Georgia, serif"
    "type_header_spacing" = "150"
    "type_header_line_height" = 1.2
    "type_header_capitalize" = $false
    "type_headers_align_text" = "center"
    "type_base_size" = 17
    "type_navigation_style" = "body"
    "type_navigation_size" = 13
    "type_navigation_capitalize" = $false
    "type_product_capitalize" = $false
    "type_collection_size" = 22
    "button_style" = "round-slight"
    "icon_weight" = "2px"
    "icon_linecaps" = "round"
  }
}

# Add new presets to existing presets
foreach ($key in $presets.Keys) {
  $json.presets | Add-Member -NotePropertyName $key -NotePropertyValue ([PSCustomObject]$presets[$key])
}

# Convert back to JSON with no formatting (single line, consistent with Shopify's format)
$output = $json | ConvertTo-Json -Depth 10 -Compress

Set-Content -Path $settingsPath -Value $output -NoNewline -Encoding UTF8
Write-Output "Added 4 presets. Total presets: $($json.presets.PSObject.Properties.Name.Count)"
$json.presets.PSObject.Properties.Name | Write-Output